### ISSUE TITLE
cpPivotJoint jitter?

### ISSUE THREAD

**Issue by navigator117** [slembcke/Chipmunk2D#174]
I'm trying to move dynamic body with mouse input and still keep body response to simulation.
the dynamic body is connect with a kinematic body by pivot joint. after read the souce code, I know set kinematic body to new position will move dynamic body to the position gradually with velocity keep in sync and position 'drift' biased. so I set kinematic body to the position every time user mouse click to the new position.
Then I found if I set maxFoce of pivot joint to a high value like Infinity, and click with reverse position to current dynamic body's move direction, the dynamic body will jitter (It may due to a suddenly velocity change) and turn move direction then. if I set maxForce to some low value the jitter gone, but the acceleration was too slow like a damping spring effect, that was not I want.
Is there a proper way to move dynamic body and turn it's direction quickly, but still keep simulation stable?

**Comment by slembcke** [comment]
Sorry for the late reply. Unfortunately I've never found an ideal way to handle this. It's pretty necessary to set some non-infinite limit to the correction force when applying using input. Otherwise you end up with a lot of sudden starts and stops every couple frames. (Mouse input is not always as smooth as you think)

There's probably some smart way to do it by multiplying some filter coefficient against the apparent mass at the joint's anchor, but I've never gotten around to trying it. Until then, multiplying against the object's mass might be the best you can do.
